import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import { MantineProvider,mantineHtmlProps ,ColorSchemeScript} from "@mantine/core";

export const metadata = {
  title: "VideoDubber.ai",
  description: "Generated by create next app",
};




export default function RootLayout({ children }) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
      <ColorSchemeScript />
      </head>
      <body>
        {/* Wrap your app with MantineProvider */}
        <MantineProvider withGlobalStyles withNormalizeCSS>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
